name: Build
# makes little sense, spell-checker: disable
on:
  pull_request:
  push:

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python_version:
            - '3.10'
    name: Windows Python ${{ matrix.python_version }}
    steps:
      - uses: actions/checkout@v2

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Use Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: 🧳 Install dependencies
        run: |
          echo y | pip install --no-python-version-warning --disable-pip-version-check nuitka
          echo y | pip install --no-python-version-warning --disable-pip-version-check zstandard
          echo y | pip install --no-python-version-warning --disable-pip-version-check pygame

      - name: Show nuitka version
        run: |
          Get-ChildItem env:
          python -m nuitka --version

      - name: Build pypvz package
        run: |
          echo y | python -m nuitka --standalone --onefile --show-progress --show-memory --output-dir=out --windows-icon-from-ico=pypvz.ico --include-data-dir=resources=resources --include-data-file=c:\hostedtoolcache\windows\python\3.10.4\x64\lib\site-packages\pygame\libogg-0.dll=libogg-0.dll --include-data-file=c:\hostedtoolcache\windows\python\3.10.4\x64\lib\site-packages\pygame\libopus-0.dll=libopus-0.dll --include-data-file=c:\hostedtoolcache\windows\python\3.10.4\x64\lib\site-packages\pygame\libopusfile-0.dll=libopusfile-0.dll --include-data-file=c:\hostedtoolcache\windows\python\3.10.4\x64\lib\site-packages\pygame\libvorbisfile-3.dll=libvorbisfile-3.dll --include-data-file=c:\hostedtoolcache\windows\python\3.10.4\x64\lib\site-packages\pygame\libvorbis-0.dll=libvorbis-0.dll --windows-disable-console main.py
          mv ./out/main.exe ./out/pypvz-windows-msvc-x64.exe

      - name: "Upload binaries"
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./out
      
  release:
    needs: [Windows]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        continue-on-error: true
        with:
          path: C:/_/artifacts
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: Current
          artifacts: C:/_/artifacts/*/*.exe
          token: ${{ secrets.GITHUB_TOKEN }}
